### ISSUE TITLE
ValueError: math domain error while running cm.print_stats()

### ISSUE THREAD

**Issue by Preetixen** [pandas-ml/pandas_confusion#14]
Hi,

I have installed `pandas_confusion`. It shown cm correctly. but error comes while calling print_stats()
Please help.

Here is some info:

```python
In [921]: y_train
Out[921]: array([2, 2, 2, ..., 4, 4, 4])

In [922]: predd
Out[922]: array([2, 1, 2, ..., 4, 5, 4])

In [923]: cm.print_stats()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-923-f061aaa93a3e> in <module>()
----> 1 cm.print_stats()
;..
  
.

841     @property

ValueError: math domain error
```

**Comment by scls19fr** [comment]
Could you display `list(y_train)` and `list(predd)` ?

```python

In [1]: from pandas_confusion import ConfusionMatrix

In [2]: import numpy as np

In [3]: y_true = np.array([2, 2, 2, 4, 4, 4])

In [4]: y_pred = np.array([2, 1, 2, 4, 5, 4])

In [5]: cm = confusion_matrix = ConfusionMatrix(y_true, y_pred)

In [6]: cm.print_stats()
Confusion Matrix:

Predicted  1  2  4  5  __all__
Actual
1          0  0  0  0        0
2          1  2  0  0        3
4          0  0  2  1        3
5          0  0  0  0        0
__all__    1  2  2  1        6


Overall Statistics:

Accuracy: 0.666666666667
95% CI: (0.22277809550351216, 0.95672813170725834)
No Information Rate: ToDo
P-Value [Acc > NIR]: 0.100137174211
Kappa: 0.5
Mcnemar's Test P-Value: ToDo


Class Statistics:

Classes                                       1         2         4         5
Population                                    6         6         6         6
P: Condition positive                         0         3         3         0
N: Condition negative                         6         3         3         6
Test outcome positive                         1         2         2         1
Test outcome negative                         5         4         4         5
TP: True Positive                             0         2         2         0
TN: True Negative                             5         3         3         5
FP: False Positive                            1         0         0         1
FN: False Negative                            0         1         1         0
TPR: (Sensitivity, hit rate, recall)        NaN  0.666667  0.666667       NaN
TNR=SPC: (Specificity)                 0.833333         1         1  0.833333
PPV: Pos Pred Value (Precision)               0         1         1         0
NPV: Neg Pred Value                           1      0.75      0.75         1
FPR: False-out                         0.166667         0         0  0.166667
FDR: False Discovery Rate                     1         0         0         1
FNR: Miss Rate                              NaN  0.333333  0.333333       NaN
ACC: Accuracy                          0.833333  0.833333  0.833333  0.833333
F1 score                                      0       0.8       0.8         0
MCC: Matthews correlation coefficient       NaN  0.707107  0.707107       NaN
Informedness                                NaN  0.666667  0.666667       NaN
Markedness                                    0      0.75      0.75         0
Prevalence                                    0       0.5       0.5         0
LR+: Positive likelihood ratio              NaN       inf       inf       NaN
LR-: Negative likelihood ratio              NaN  0.333333  0.333333       NaN
DOR: Diagnostic odds ratio                  NaN       inf       inf       NaN
FOR: False omission rate                      0      0.25      0.25         0
```

**Comment by Preetixen** [comment]
In [569]: y_train=lb.fit_transform(y_train)
In [570]: y_train.dtype
Out[570]: dtype('int64')

In [571]: predd=lb.fit_transform(predd)
In [572]: predd.dtype
Out[572]: dtype('int64')

In [573]: predd.shape
Out[573]: (513391,)

In [574]: predd.shape
Out[574]: (513391,)

In [575]: predd
Out[575]: array([2, 2, 2, ..., 4, 4, 4])

In [576]: y_train
Out[576]: array([2, 2, 2, ..., 4, 4, 4])

**Comment by Preetixen** [comment]
In [738]: cm = confusion_matrix = ConfusionMatrix(y_train, predd)

In [739]: predd
Out[739]: array([9, 3, 3, ..., 9, 9, 9])

In [740]: y_train
Out[740]: array([10,  9,  9, ...,  9,  9,  9])

In [741]: predd.dtype
Out[741]: dtype('int64')

In [742]: predd.shape
Out[742]: (700002,)

In [743]: y_train.dtype
Out[743]: dtype('int64')

In [744]: y_train.shape
Out[744]: (700002,)

In [745]: y_train
Out[745]: array([10,  9,  9, ...,  9,  9,  9])

In [746]: cm = confusion_matrix = ConfusionMatrix(y_train, predd)

In [747]: cm.print_stats()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-747-f061aaa93a3e> in <module>()
----> 1 cm.print_stats()

/usr/local/lib/python2.7/dist-packages/pandas_confusion-0.0.6-py2.7.egg/pandas_confusion/__init__.pyc in print_stats(self, lst_stats)
    468         Prints statistics
    469         """
--> 470         print(self._str_stats(lst_stats))
    471 
    472     def get(self, actual=None, predicted=None):

/usr/local/lib/python2.7/dist-packages/pandas_confusion-0.0.6-py2.7.egg/pandas_confusion/__init__.pyc in _str_stats(self, lst_stats)
    449         }
    450 
--> 451         stats = self.stats(lst_stats)
    452 
    453         d_stats_str = collections.OrderedDict([

/usr/local/lib/python2.7/dist-packages/pandas_confusion-0.0.6-py2.7.egg/pandas_confusion/__init__.pyc in stats(self, lst_stats)
    413         d_stats['cm'] = self
    414         d_stats['overall'] = self.stats_overall
--> 415         d_stats['class'] = self.stats_class
    416         return(d_stats)
    417 

/usr/local/lib/python2.7/dist-packages/pandas_confusion-0.0.6-py2.7.egg/pandas_confusion/__init__.pyc in stats_class(self)
    367         for cls in self.classes:
    368             binary_cm = self.binarize(cls)
--> 369             binary_cm_stats = binary_cm.stats()
    370             for key, value in binary_cm_stats.items():
    371                 df.loc[key, cls] = value  # binary_cm_stats

/usr/local/lib/python2.7/dist-packages/pandas_confusion-0.0.6-py2.7.egg/pandas_confusion/__init__.pyc in stats(self, lst_stats)
    891                 'FNR', 'ACC', 'F1_score', 'MCC', 'informedness', 'markedness',
    892                 'prevalence', 'LRP', 'LRN', 'DOR', 'FOR']
--> 893         d = map(lambda stat: (stat, getattr(self, stat)), lst_stats)
    894         return(collections.OrderedDict(d))
    895 

/usr/local/lib/python2.7/dist-packages/pandas_confusion-0.0.6-py2.7.egg/pandas_confusion/__init__.pyc in <lambda>(stat)
    891                 'FNR', 'ACC', 'F1_score', 'MCC', 'informedness', 'markedness',
    892                 'prevalence', 'LRP', 'LRN', 'DOR', 'FOR']
--> 893         d = map(lambda stat: (stat, getattr(self, stat)), lst_stats)
    894         return(collections.OrderedDict(d))
    895 

/usr/local/lib/python2.7/dist-packages/pandas_confusion-0.0.6-py2.7.egg/pandas_confusion/__init__.pyc in MCC(self)
    837         return((self.TP * self.TN - self.FP * self.FN) /
    838                math.sqrt((self.TP + self.FP) * (self.TP + self.FN) *
--> 839                (self.TN + self.FP) * (self.TN + self.FN)))
    840 
    841     @property

ValueError: math domain error

In [748]: cm
Out[748]: 
Predicted     0     1    2      3     4     5     6    7   8       9  10  \
Actual                                                                     
0          1378   752   87    103   186    31    33    2  13    2466   0   
1           379    38   40      0    17     0     0    0   0      52   0   
2           380    56   18     16    43     3     7    4   0       7   0   
3           304   168   64    106   393    62    34    9   5      22   0   
4           146   759  146    468  3281   208   238   26  39      98   0   
5            17     2    6     90   270  7088    13   25   3       8   0   
6            15     0    7     37   128     7  1556    0   3       6   0   
7             3     0    2     11    35     3     0  164   0       5   0   
8             0     0    0      1    14     3     2    0   4       0   0   
9          3184   277   13  47405   516    34    22    7   6  626322   0   
10            0     0    0      0     0     0     0    0   0       1   0   
__all__    5806  2052  383  48237  4883  7439  1905  237  73  628987   0   

Predicted  __all__  
Actual              
0             5051  
1              526  
2              534  
3             1167  
4             5409  
5             7522  
6             1759  
7              223  
8               24  
9           677786  
10               1  
__all__     700002

**Comment by Preetixen** [comment]
![screenshot from 2016-05-06 09-07-38](https://cloud.githubusercontent.com/assets/16998342/15063741/01a3e2c2-136a-11e6-9cc4-4ba2646e5418.png)

**Comment by scls19fr** [comment]
I'm sorry but I won't be able to reproduce this bug if I don't have data.
Please paste content of `y_train` and `predd`

**Comment by Preetixen** [comment]
Hi,

Sure.
Here are my files

**Comment by scls19fr** [comment]
`ConfusionMatrix` is moving to https://github.com/pandas-ml/pandas-ml
