### ISSUE TITLE
precision and recall

### ISSUE THREAD

**Issue by vinayakumarr** [pandas-ml/pandas_confusion#17]
I have been using you library  and i want to know, how to calculate precision and recall?

**Comment by scls19fr** [comment]
Hi @vinayakumarr 

I know doc is not enought...
so you might have a look at code !

see https://github.com/pandas-ml/pandas_confusion/blob/master/pandas_confusion/__init__.py

'TPR': 'TPR: (Sensitivity, hit rate, recall)',  # True Positive Rate
'PPV': 'PPV: Pos Pred Value (Precision)',

so if `cm` is your binary confusion matrix 

you can get `recall` using

```python
cm.recall
```
or 

```python
cm.TPR
```

You can get `precision` using


```python
cm.precision
```
or 

```python
cm.PPV
```

Hope that helps

**Comment by scls19fr** [comment]
`ConfusionMatrix` is now part of https://github.com/pandas-ml/pandas-ml
